// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nest/market-models/mono/monoDispute.proto

package market_models

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MonoEvidence defines evidence for a dispute/rebutal in the mono marketplace
type MonoEvidence struct {
	EvidenceId   uint64 `protobuf:"varint,1,opt,name=evidenceId,proto3" json:"evidenceId,omitempty"`
	DisputeId    uint64 `protobuf:"varint,2,opt,name=disputeId,proto3" json:"disputeId,omitempty"`
	ExternalLink string `protobuf:"bytes,3,opt,name=externalLink,proto3" json:"externalLink,omitempty"`
}

func (m *MonoEvidence) Reset()         { *m = MonoEvidence{} }
func (m *MonoEvidence) String() string { return proto.CompactTextString(m) }
func (*MonoEvidence) ProtoMessage()    {}
func (*MonoEvidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_1be600aaa49bca9e, []int{0}
}
func (m *MonoEvidence) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MonoEvidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MonoEvidence.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MonoEvidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonoEvidence.Merge(m, src)
}
func (m *MonoEvidence) XXX_Size() int {
	return m.Size()
}
func (m *MonoEvidence) XXX_DiscardUnknown() {
	xxx_messageInfo_MonoEvidence.DiscardUnknown(m)
}

var xxx_messageInfo_MonoEvidence proto.InternalMessageInfo

func (m *MonoEvidence) GetEvidenceId() uint64 {
	if m != nil {
		return m.EvidenceId
	}
	return 0
}

func (m *MonoEvidence) GetDisputeId() uint64 {
	if m != nil {
		return m.DisputeId
	}
	return 0
}

func (m *MonoEvidence) GetExternalLink() string {
	if m != nil {
		return m.ExternalLink
	}
	return ""
}

//MonoRebuttal defines the rebutal for a raised dispute in the mono marketplace
type MonoRebuttal struct {
	RebuttalId uint64        `protobuf:"varint,1,opt,name=rebuttalId,proto3" json:"rebuttalId,omitempty"`
	DisputeId  uint64        `protobuf:"varint,2,opt,name=disputeId,proto3" json:"disputeId,omitempty"`
	Evidence   *MonoEvidence `protobuf:"bytes,3,opt,name=evidence,proto3" json:"evidence,omitempty"`
}

func (m *MonoRebuttal) Reset()         { *m = MonoRebuttal{} }
func (m *MonoRebuttal) String() string { return proto.CompactTextString(m) }
func (*MonoRebuttal) ProtoMessage()    {}
func (*MonoRebuttal) Descriptor() ([]byte, []int) {
	return fileDescriptor_1be600aaa49bca9e, []int{1}
}
func (m *MonoRebuttal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MonoRebuttal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MonoRebuttal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MonoRebuttal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonoRebuttal.Merge(m, src)
}
func (m *MonoRebuttal) XXX_Size() int {
	return m.Size()
}
func (m *MonoRebuttal) XXX_DiscardUnknown() {
	xxx_messageInfo_MonoRebuttal.DiscardUnknown(m)
}

var xxx_messageInfo_MonoRebuttal proto.InternalMessageInfo

func (m *MonoRebuttal) GetRebuttalId() uint64 {
	if m != nil {
		return m.RebuttalId
	}
	return 0
}

func (m *MonoRebuttal) GetDisputeId() uint64 {
	if m != nil {
		return m.DisputeId
	}
	return 0
}

func (m *MonoRebuttal) GetEvidence() *MonoEvidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

//monoDispute defines a dispute over a mono markeplace exchange of physical goods
type MonoDispute struct {
	DiputeId    uint64        `protobuf:"varint,1,opt,name=diputeId,proto3" json:"diputeId,omitempty"`
	Title       string        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Evidence    *MonoEvidence `protobuf:"bytes,4,opt,name=evidence,proto3" json:"evidence,omitempty"`
}

func (m *MonoDispute) Reset()         { *m = MonoDispute{} }
func (m *MonoDispute) String() string { return proto.CompactTextString(m) }
func (*MonoDispute) ProtoMessage()    {}
func (*MonoDispute) Descriptor() ([]byte, []int) {
	return fileDescriptor_1be600aaa49bca9e, []int{2}
}
func (m *MonoDispute) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MonoDispute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MonoDispute.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MonoDispute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonoDispute.Merge(m, src)
}
func (m *MonoDispute) XXX_Size() int {
	return m.Size()
}
func (m *MonoDispute) XXX_DiscardUnknown() {
	xxx_messageInfo_MonoDispute.DiscardUnknown(m)
}

var xxx_messageInfo_MonoDispute proto.InternalMessageInfo

func (m *MonoDispute) GetDiputeId() uint64 {
	if m != nil {
		return m.DiputeId
	}
	return 0
}

func (m *MonoDispute) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MonoDispute) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MonoDispute) GetEvidence() *MonoEvidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

// MonoFundDistribution defines a structure to divide distributed funds in
type MonoFundDistribution struct {
	PlaintifAmount  []types.Coin `protobuf:"bytes,1,rep,name=plaintifAmount,proto3" json:"plaintifAmount"`
	DefendantAmount []types.Coin `protobuf:"bytes,2,rep,name=defendantAmount,proto3" json:"defendantAmount"`
}

func (m *MonoFundDistribution) Reset()         { *m = MonoFundDistribution{} }
func (m *MonoFundDistribution) String() string { return proto.CompactTextString(m) }
func (*MonoFundDistribution) ProtoMessage()    {}
func (*MonoFundDistribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_1be600aaa49bca9e, []int{3}
}
func (m *MonoFundDistribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MonoFundDistribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MonoFundDistribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MonoFundDistribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonoFundDistribution.Merge(m, src)
}
func (m *MonoFundDistribution) XXX_Size() int {
	return m.Size()
}
func (m *MonoFundDistribution) XXX_DiscardUnknown() {
	xxx_messageInfo_MonoFundDistribution.DiscardUnknown(m)
}

var xxx_messageInfo_MonoFundDistribution proto.InternalMessageInfo

func (m *MonoFundDistribution) GetPlaintifAmount() []types.Coin {
	if m != nil {
		return m.PlaintifAmount
	}
	return nil
}

func (m *MonoFundDistribution) GetDefendantAmount() []types.Coin {
	if m != nil {
		return m.DefendantAmount
	}
	return nil
}

// MonoSentence defines the outcome of a dispute
type MonoSentence struct {
	VoteId               uint64                `protobuf:"varint,1,opt,name=voteId,proto3" json:"voteId,omitempty"`
	PlaintifGuilty       bool                  `protobuf:"varint,2,opt,name=plaintifGuilty,proto3" json:"plaintifGuilty,omitempty"`
	DefendantGuilty      bool                  `protobuf:"varint,3,opt,name=defendantGuilty,proto3" json:"defendantGuilty,omitempty"`
	PlainttifBlacklisted bool                  `protobuf:"varint,4,opt,name=plainttifBlacklisted,proto3" json:"plainttifBlacklisted,omitempty"`
	DefendantBlacklisted bool                  `protobuf:"varint,5,opt,name=defendantBlacklisted,proto3" json:"defendantBlacklisted,omitempty"`
	FundDistr            *MonoFundDistribution `protobuf:"bytes,6,opt,name=fundDistr,proto3" json:"fundDistr,omitempty"`
}

func (m *MonoSentence) Reset()         { *m = MonoSentence{} }
func (m *MonoSentence) String() string { return proto.CompactTextString(m) }
func (*MonoSentence) ProtoMessage()    {}
func (*MonoSentence) Descriptor() ([]byte, []int) {
	return fileDescriptor_1be600aaa49bca9e, []int{4}
}
func (m *MonoSentence) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MonoSentence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MonoSentence.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MonoSentence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonoSentence.Merge(m, src)
}
func (m *MonoSentence) XXX_Size() int {
	return m.Size()
}
func (m *MonoSentence) XXX_DiscardUnknown() {
	xxx_messageInfo_MonoSentence.DiscardUnknown(m)
}

var xxx_messageInfo_MonoSentence proto.InternalMessageInfo

func (m *MonoSentence) GetVoteId() uint64 {
	if m != nil {
		return m.VoteId
	}
	return 0
}

func (m *MonoSentence) GetPlaintifGuilty() bool {
	if m != nil {
		return m.PlaintifGuilty
	}
	return false
}

func (m *MonoSentence) GetDefendantGuilty() bool {
	if m != nil {
		return m.DefendantGuilty
	}
	return false
}

func (m *MonoSentence) GetPlainttifBlacklisted() bool {
	if m != nil {
		return m.PlainttifBlacklisted
	}
	return false
}

func (m *MonoSentence) GetDefendantBlacklisted() bool {
	if m != nil {
		return m.DefendantBlacklisted
	}
	return false
}

func (m *MonoSentence) GetFundDistr() *MonoFundDistribution {
	if m != nil {
		return m.FundDistr
	}
	return nil
}

// MonoVote defines the vote that is cast for a MonoDispute
type MonoVote struct {
	VoterId   uint64        `protobuf:"varint,1,opt,name=voterId,proto3" json:"voterId,omitempty"`
	DisputeId uint64        `protobuf:"varint,2,opt,name=disputeId,proto3" json:"disputeId,omitempty"`
	BuyerId   *MonoSentence `protobuf:"bytes,3,opt,name=buyerId,proto3" json:"buyerId,omitempty"`
}

func (m *MonoVote) Reset()         { *m = MonoVote{} }
func (m *MonoVote) String() string { return proto.CompactTextString(m) }
func (*MonoVote) ProtoMessage()    {}
func (*MonoVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_1be600aaa49bca9e, []int{5}
}
func (m *MonoVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MonoVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MonoVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MonoVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonoVote.Merge(m, src)
}
func (m *MonoVote) XXX_Size() int {
	return m.Size()
}
func (m *MonoVote) XXX_DiscardUnknown() {
	xxx_messageInfo_MonoVote.DiscardUnknown(m)
}

var xxx_messageInfo_MonoVote proto.InternalMessageInfo

func (m *MonoVote) GetVoterId() uint64 {
	if m != nil {
		return m.VoterId
	}
	return 0
}

func (m *MonoVote) GetDisputeId() uint64 {
	if m != nil {
		return m.DisputeId
	}
	return 0
}

func (m *MonoVote) GetBuyerId() *MonoSentence {
	if m != nil {
		return m.BuyerId
	}
	return nil
}

func init() {
	proto.RegisterType((*MonoEvidence)(nil), "crowlabs.epsilon.nest.marketmodels.mono.MonoEvidence")
	proto.RegisterType((*MonoRebuttal)(nil), "crowlabs.epsilon.nest.marketmodels.mono.MonoRebuttal")
	proto.RegisterType((*MonoDispute)(nil), "crowlabs.epsilon.nest.marketmodels.mono.MonoDispute")
	proto.RegisterType((*MonoFundDistribution)(nil), "crowlabs.epsilon.nest.marketmodels.mono.MonoFundDistribution")
	proto.RegisterType((*MonoSentence)(nil), "crowlabs.epsilon.nest.marketmodels.mono.MonoSentence")
	proto.RegisterType((*MonoVote)(nil), "crowlabs.epsilon.nest.marketmodels.mono.MonoVote")
}

func init() {
	proto.RegisterFile("nest/market-models/mono/monoDispute.proto", fileDescriptor_1be600aaa49bca9e)
}

var fileDescriptor_1be600aaa49bca9e = []byte{
	// 576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x6e, 0xd6, 0xae, 0x6b, 0xdd, 0x09, 0x24, 0xab, 0x42, 0xa1, 0x42, 0xa1, 0xca, 0x01, 0xca,
	0x61, 0x8e, 0x5a, 0xc4, 0x91, 0x03, 0x65, 0x30, 0x55, 0x30, 0x21, 0x82, 0xc4, 0x01, 0x4e, 0x49,
	0xec, 0x16, 0xab, 0x89, 0x1d, 0xc5, 0x4e, 0xd9, 0xfe, 0x05, 0x12, 0x3f, 0x80, 0x3b, 0x67, 0xae,
	0xdc, 0x77, 0xdc, 0x91, 0x13, 0x42, 0xed, 0x1f, 0x41, 0xb6, 0xd3, 0x26, 0x2b, 0x93, 0x36, 0x10,
	0x97, 0xca, 0xef, 0x7b, 0xfe, 0xde, 0xf7, 0xf5, 0xbd, 0x17, 0x83, 0x07, 0x8c, 0x08, 0xe9, 0x25,
	0x41, 0x36, 0x27, 0xf2, 0x20, 0xe1, 0x98, 0xc4, 0xc2, 0x4b, 0x38, 0xe3, 0xfa, 0xe7, 0x90, 0x8a,
	0x34, 0x97, 0x04, 0xa5, 0x19, 0x97, 0x1c, 0xde, 0x8f, 0x32, 0xfe, 0x31, 0x0e, 0x42, 0x81, 0x48,
	0x2a, 0x68, 0xcc, 0x19, 0x52, 0x5c, 0x64, 0xb8, 0x86, 0x8a, 0x14, 0xab, 0xe7, 0x44, 0x5c, 0x24,
	0x5c, 0x78, 0x61, 0x20, 0x88, 0xb7, 0x18, 0x86, 0x44, 0x06, 0x43, 0x2f, 0xe2, 0x94, 0x99, 0x42,
	0xbd, 0xee, 0x8c, 0xcf, 0xb8, 0x3e, 0x7a, 0xea, 0x64, 0x50, 0x37, 0x05, 0xfb, 0xc7, 0x9c, 0xf1,
	0x67, 0x0b, 0x8a, 0x09, 0x8b, 0x08, 0x74, 0x00, 0x20, 0xc5, 0x79, 0x82, 0x6d, 0xab, 0x6f, 0x0d,
	0x1a, 0x7e, 0x05, 0x81, 0x77, 0x40, 0x1b, 0x1b, 0x7f, 0x13, 0x6c, 0xef, 0xe8, 0x74, 0x09, 0x40,
	0x17, 0xec, 0x93, 0x13, 0x49, 0x32, 0x16, 0xc4, 0x2f, 0x29, 0x9b, 0xdb, 0xf5, 0xbe, 0x35, 0x68,
	0xfb, 0x17, 0x30, 0xf7, 0x8b, 0x65, 0x24, 0x7d, 0x12, 0xe6, 0x52, 0x06, 0xb1, 0x92, 0xcc, 0x8a,
	0x73, 0x29, 0x59, 0x22, 0x57, 0x48, 0xbe, 0x06, 0xad, 0xb5, 0x3d, 0x2d, 0xd7, 0x19, 0x3d, 0x42,
	0xd7, 0x6c, 0x19, 0xaa, 0xfe, 0x73, 0x7f, 0x53, 0xc6, 0xfd, 0x66, 0x81, 0xce, 0x71, 0x39, 0x08,
	0xd8, 0x03, 0x2d, 0x4c, 0x0b, 0x7d, 0x63, 0x6f, 0x13, 0xc3, 0x2e, 0xd8, 0x95, 0x54, 0xc6, 0x44,
	0x1b, 0x6b, 0xfb, 0x26, 0x80, 0x7d, 0xd0, 0xc1, 0x44, 0x44, 0x19, 0x4d, 0x25, 0xe5, 0xac, 0x68,
	0x43, 0x15, 0xba, 0x60, 0xbb, 0xf1, 0x7f, 0x6c, 0x7f, 0xb5, 0x40, 0x57, 0xa5, 0x9e, 0xe7, 0x0c,
	0x1f, 0x52, 0x21, 0x33, 0x1a, 0xe6, 0x5a, 0xeb, 0x08, 0xdc, 0x48, 0xe3, 0x80, 0x32, 0x49, 0xa7,
	0x4f, 0x12, 0x9e, 0x33, 0x69, 0x5b, 0xfd, 0xfa, 0xa0, 0x33, 0xba, 0x8d, 0xcc, 0xca, 0x20, 0xb5,
	0x32, 0xa8, 0x58, 0x19, 0xf4, 0x94, 0x53, 0x36, 0x6e, 0x9c, 0xfd, 0xbc, 0x5b, 0xf3, 0xb7, 0x68,
	0x70, 0x02, 0x6e, 0x62, 0x32, 0x25, 0x0c, 0x07, 0x4c, 0x16, 0x95, 0x76, 0xae, 0x57, 0x69, 0x9b,
	0xe7, 0x7e, 0xdf, 0x31, 0x5b, 0xf0, 0x86, 0x30, 0xa9, 0x17, 0xef, 0x16, 0x68, 0x2e, 0x78, 0xa5,
	0xc5, 0x45, 0x04, 0xef, 0x95, 0xe6, 0x8f, 0x72, 0x1a, 0xcb, 0x53, 0xdd, 0xe9, 0x96, 0xbf, 0x85,
	0xc2, 0x41, 0xc5, 0x5b, 0x71, 0xb1, 0xae, 0x2f, 0x6e, 0xc3, 0x70, 0x04, 0xba, 0x86, 0x2b, 0xe9,
	0x74, 0x1c, 0x07, 0xd1, 0x3c, 0xa6, 0x42, 0x12, 0xac, 0xc7, 0xd0, 0xf2, 0x2f, 0xcd, 0x29, 0xce,
	0xa6, 0x4c, 0x95, 0xb3, 0x6b, 0x38, 0x97, 0xe5, 0xe0, 0x7b, 0xd0, 0x9e, 0xae, 0x47, 0x61, 0x37,
	0xf5, 0x8c, 0x1f, 0xff, 0xd5, 0x8c, 0xb7, 0x07, 0xe9, 0x97, 0xf5, 0xdc, 0xcf, 0x16, 0x68, 0xa9,
	0x3b, 0x6f, 0xb9, 0x24, 0xd0, 0x06, 0x7b, 0xaa, 0x5b, 0xd9, 0xa6, 0x79, 0xeb, 0xf0, 0x8a, 0x6f,
	0xe7, 0x15, 0xd8, 0x0b, 0xf3, 0x53, 0xcd, 0xfb, 0x97, 0x4f, 0x67, 0x3d, 0x3b, 0x7f, 0x5d, 0x65,
	0xfc, 0xe2, 0x6c, 0xe9, 0x58, 0xe7, 0x4b, 0xc7, 0xfa, 0xb5, 0x74, 0xac, 0x4f, 0x2b, 0xa7, 0x76,
	0xbe, 0x72, 0x6a, 0x3f, 0x56, 0x4e, 0xed, 0xdd, 0x70, 0x46, 0xe5, 0x87, 0x3c, 0x44, 0x11, 0x4f,
	0x3c, 0xa5, 0x71, 0xa0, 0x44, 0xbc, 0x42, 0xc4, 0x3b, 0xf1, 0xfe, 0x7c, 0x10, 0xc3, 0xa6, 0x7e,
	0xa1, 0x1e, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x4b, 0x36, 0x1d, 0x2d, 0x05, 0x00, 0x00,
}

func (m *MonoEvidence) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MonoEvidence) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MonoEvidence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExternalLink) > 0 {
		i -= len(m.ExternalLink)
		copy(dAtA[i:], m.ExternalLink)
		i = encodeVarintMonoDispute(dAtA, i, uint64(len(m.ExternalLink)))
		i--
		dAtA[i] = 0x1a
	}
	if m.DisputeId != 0 {
		i = encodeVarintMonoDispute(dAtA, i, uint64(m.DisputeId))
		i--
		dAtA[i] = 0x10
	}
	if m.EvidenceId != 0 {
		i = encodeVarintMonoDispute(dAtA, i, uint64(m.EvidenceId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MonoRebuttal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MonoRebuttal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MonoRebuttal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Evidence != nil {
		{
			size, err := m.Evidence.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMonoDispute(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.DisputeId != 0 {
		i = encodeVarintMonoDispute(dAtA, i, uint64(m.DisputeId))
		i--
		dAtA[i] = 0x10
	}
	if m.RebuttalId != 0 {
		i = encodeVarintMonoDispute(dAtA, i, uint64(m.RebuttalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MonoDispute) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MonoDispute) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MonoDispute) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Evidence != nil {
		{
			size, err := m.Evidence.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMonoDispute(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintMonoDispute(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintMonoDispute(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if m.DiputeId != 0 {
		i = encodeVarintMonoDispute(dAtA, i, uint64(m.DiputeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MonoFundDistribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MonoFundDistribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MonoFundDistribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DefendantAmount) > 0 {
		for iNdEx := len(m.DefendantAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DefendantAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMonoDispute(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.PlaintifAmount) > 0 {
		for iNdEx := len(m.PlaintifAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PlaintifAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMonoDispute(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MonoSentence) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MonoSentence) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MonoSentence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FundDistr != nil {
		{
			size, err := m.FundDistr.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMonoDispute(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.DefendantBlacklisted {
		i--
		if m.DefendantBlacklisted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.PlainttifBlacklisted {
		i--
		if m.PlainttifBlacklisted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.DefendantGuilty {
		i--
		if m.DefendantGuilty {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.PlaintifGuilty {
		i--
		if m.PlaintifGuilty {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.VoteId != 0 {
		i = encodeVarintMonoDispute(dAtA, i, uint64(m.VoteId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MonoVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MonoVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MonoVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BuyerId != nil {
		{
			size, err := m.BuyerId.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMonoDispute(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.DisputeId != 0 {
		i = encodeVarintMonoDispute(dAtA, i, uint64(m.DisputeId))
		i--
		dAtA[i] = 0x10
	}
	if m.VoterId != 0 {
		i = encodeVarintMonoDispute(dAtA, i, uint64(m.VoterId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMonoDispute(dAtA []byte, offset int, v uint64) int {
	offset -= sovMonoDispute(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MonoEvidence) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EvidenceId != 0 {
		n += 1 + sovMonoDispute(uint64(m.EvidenceId))
	}
	if m.DisputeId != 0 {
		n += 1 + sovMonoDispute(uint64(m.DisputeId))
	}
	l = len(m.ExternalLink)
	if l > 0 {
		n += 1 + l + sovMonoDispute(uint64(l))
	}
	return n
}

func (m *MonoRebuttal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RebuttalId != 0 {
		n += 1 + sovMonoDispute(uint64(m.RebuttalId))
	}
	if m.DisputeId != 0 {
		n += 1 + sovMonoDispute(uint64(m.DisputeId))
	}
	if m.Evidence != nil {
		l = m.Evidence.Size()
		n += 1 + l + sovMonoDispute(uint64(l))
	}
	return n
}

func (m *MonoDispute) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DiputeId != 0 {
		n += 1 + sovMonoDispute(uint64(m.DiputeId))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovMonoDispute(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovMonoDispute(uint64(l))
	}
	if m.Evidence != nil {
		l = m.Evidence.Size()
		n += 1 + l + sovMonoDispute(uint64(l))
	}
	return n
}

func (m *MonoFundDistribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PlaintifAmount) > 0 {
		for _, e := range m.PlaintifAmount {
			l = e.Size()
			n += 1 + l + sovMonoDispute(uint64(l))
		}
	}
	if len(m.DefendantAmount) > 0 {
		for _, e := range m.DefendantAmount {
			l = e.Size()
			n += 1 + l + sovMonoDispute(uint64(l))
		}
	}
	return n
}

func (m *MonoSentence) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VoteId != 0 {
		n += 1 + sovMonoDispute(uint64(m.VoteId))
	}
	if m.PlaintifGuilty {
		n += 2
	}
	if m.DefendantGuilty {
		n += 2
	}
	if m.PlainttifBlacklisted {
		n += 2
	}
	if m.DefendantBlacklisted {
		n += 2
	}
	if m.FundDistr != nil {
		l = m.FundDistr.Size()
		n += 1 + l + sovMonoDispute(uint64(l))
	}
	return n
}

func (m *MonoVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VoterId != 0 {
		n += 1 + sovMonoDispute(uint64(m.VoterId))
	}
	if m.DisputeId != 0 {
		n += 1 + sovMonoDispute(uint64(m.DisputeId))
	}
	if m.BuyerId != nil {
		l = m.BuyerId.Size()
		n += 1 + l + sovMonoDispute(uint64(l))
	}
	return n
}

func sovMonoDispute(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMonoDispute(x uint64) (n int) {
	return sovMonoDispute(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MonoEvidence) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonoDispute
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MonoEvidence: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MonoEvidence: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvidenceId", wireType)
			}
			m.EvidenceId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EvidenceId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeId", wireType)
			}
			m.DisputeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExternalLink", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMonoDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExternalLink = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMonoDispute(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MonoRebuttal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonoDispute
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MonoRebuttal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MonoRebuttal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RebuttalId", wireType)
			}
			m.RebuttalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RebuttalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeId", wireType)
			}
			m.DisputeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonoDispute
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Evidence == nil {
				m.Evidence = &MonoEvidence{}
			}
			if err := m.Evidence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMonoDispute(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MonoDispute) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonoDispute
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MonoDispute: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MonoDispute: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DiputeId", wireType)
			}
			m.DiputeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DiputeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMonoDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMonoDispute
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Evidence", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonoDispute
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Evidence == nil {
				m.Evidence = &MonoEvidence{}
			}
			if err := m.Evidence.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMonoDispute(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MonoFundDistribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonoDispute
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MonoFundDistribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MonoFundDistribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlaintifAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonoDispute
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlaintifAmount = append(m.PlaintifAmount, types.Coin{})
			if err := m.PlaintifAmount[len(m.PlaintifAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefendantAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonoDispute
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefendantAmount = append(m.DefendantAmount, types.Coin{})
			if err := m.DefendantAmount[len(m.DefendantAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMonoDispute(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MonoSentence) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonoDispute
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MonoSentence: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MonoSentence: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteId", wireType)
			}
			m.VoteId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VoteId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlaintifGuilty", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PlaintifGuilty = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefendantGuilty", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DefendantGuilty = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlainttifBlacklisted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PlainttifBlacklisted = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefendantBlacklisted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DefendantBlacklisted = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FundDistr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonoDispute
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FundDistr == nil {
				m.FundDistr = &MonoFundDistribution{}
			}
			if err := m.FundDistr.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMonoDispute(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MonoVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonoDispute
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MonoVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MonoVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoterId", wireType)
			}
			m.VoterId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VoterId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisputeId", wireType)
			}
			m.DisputeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisputeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonoDispute
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BuyerId == nil {
				m.BuyerId = &MonoSentence{}
			}
			if err := m.BuyerId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMonoDispute(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonoDispute
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMonoDispute(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMonoDispute
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMonoDispute
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMonoDispute
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMonoDispute
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMonoDispute
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMonoDispute        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMonoDispute          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMonoDispute = fmt.Errorf("proto: unexpected end of group")
)
