// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nest/market-models/mono/monoMarketplace.proto

package market_models

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MonoItem defines an item on the mono marketplace, listed by a mono seller
type MonoItem struct {
	ItemId        uint64       `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Title         string       `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SellerAddress string       `protobuf:"bytes,4,opt,name=sellerAddress,proto3" json:"sellerAddress,omitempty"`
	MinPrice      []types.Coin `protobuf:"bytes,5,rep,name=minPrice,proto3" json:"minPrice"`
	Collateral    []types.Coin `protobuf:"bytes,6,rep,name=collateral,proto3" json:"collateral"`
}

func (m *MonoItem) Reset()         { *m = MonoItem{} }
func (m *MonoItem) String() string { return proto.CompactTextString(m) }
func (*MonoItem) ProtoMessage()    {}
func (*MonoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_14097fc8f155190e, []int{0}
}
func (m *MonoItem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MonoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MonoItem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MonoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonoItem.Merge(m, src)
}
func (m *MonoItem) XXX_Size() int {
	return m.Size()
}
func (m *MonoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MonoItem.DiscardUnknown(m)
}

var xxx_messageInfo_MonoItem proto.InternalMessageInfo

func (m *MonoItem) GetItemId() uint64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *MonoItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MonoItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MonoItem) GetSellerAddress() string {
	if m != nil {
		return m.SellerAddress
	}
	return ""
}

func (m *MonoItem) GetMinPrice() []types.Coin {
	if m != nil {
		return m.MinPrice
	}
	return nil
}

func (m *MonoItem) GetCollateral() []types.Coin {
	if m != nil {
		return m.Collateral
	}
	return nil
}

// MonoSellOrder defines the sell order placed by a seller in the mono marketplace
type MonoSellOrder struct {
	SellOrderId uint64 `protobuf:"varint,1,opt,name=sellOrderId,proto3" json:"sellOrderId,omitempty"`
	SellerId    uint64 `protobuf:"varint,2,opt,name=sellerId,proto3" json:"sellerId,omitempty"`
	ItemId      uint64 `protobuf:"varint,3,opt,name=itemId,proto3" json:"itemId,omitempty"`
}

func (m *MonoSellOrder) Reset()         { *m = MonoSellOrder{} }
func (m *MonoSellOrder) String() string { return proto.CompactTextString(m) }
func (*MonoSellOrder) ProtoMessage()    {}
func (*MonoSellOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_14097fc8f155190e, []int{1}
}
func (m *MonoSellOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MonoSellOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MonoSellOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MonoSellOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonoSellOrder.Merge(m, src)
}
func (m *MonoSellOrder) XXX_Size() int {
	return m.Size()
}
func (m *MonoSellOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MonoSellOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MonoSellOrder proto.InternalMessageInfo

func (m *MonoSellOrder) GetSellOrderId() uint64 {
	if m != nil {
		return m.SellOrderId
	}
	return 0
}

func (m *MonoSellOrder) GetSellerId() uint64 {
	if m != nil {
		return m.SellerId
	}
	return 0
}

func (m *MonoSellOrder) GetItemId() uint64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

// MonoBuyOrder defines the buy order placed by a buyer in the mono Marketplace
type MonoBuyOrder struct {
	BuyOrderId uint64 `protobuf:"varint,1,opt,name=buyOrderId,proto3" json:"buyOrderId,omitempty"`
	BuyerId    uint64 `protobuf:"varint,2,opt,name=buyerId,proto3" json:"buyerId,omitempty"`
	ItemId     uint64 `protobuf:"varint,3,opt,name=itemId,proto3" json:"itemId,omitempty"`
}

func (m *MonoBuyOrder) Reset()         { *m = MonoBuyOrder{} }
func (m *MonoBuyOrder) String() string { return proto.CompactTextString(m) }
func (*MonoBuyOrder) ProtoMessage()    {}
func (*MonoBuyOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_14097fc8f155190e, []int{2}
}
func (m *MonoBuyOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MonoBuyOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MonoBuyOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MonoBuyOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonoBuyOrder.Merge(m, src)
}
func (m *MonoBuyOrder) XXX_Size() int {
	return m.Size()
}
func (m *MonoBuyOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MonoBuyOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MonoBuyOrder proto.InternalMessageInfo

func (m *MonoBuyOrder) GetBuyOrderId() uint64 {
	if m != nil {
		return m.BuyOrderId
	}
	return 0
}

func (m *MonoBuyOrder) GetBuyerId() uint64 {
	if m != nil {
		return m.BuyerId
	}
	return 0
}

func (m *MonoBuyOrder) GetItemId() uint64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func init() {
	proto.RegisterType((*MonoItem)(nil), "crowlabs.epsilon.nest.marketmodels.mono.MonoItem")
	proto.RegisterType((*MonoSellOrder)(nil), "crowlabs.epsilon.nest.marketmodels.mono.MonoSellOrder")
	proto.RegisterType((*MonoBuyOrder)(nil), "crowlabs.epsilon.nest.marketmodels.mono.MonoBuyOrder")
}

func init() {
	proto.RegisterFile("nest/market-models/mono/monoMarketplace.proto", fileDescriptor_14097fc8f155190e)
}

var fileDescriptor_14097fc8f155190e = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x41, 0x8b, 0x13, 0x31,
	0x18, 0xed, 0xd8, 0x6e, 0xad, 0x59, 0xf7, 0x12, 0x16, 0x19, 0x7b, 0x88, 0xa5, 0x08, 0xf6, 0xd2,
	0x84, 0xea, 0xd1, 0x83, 0x58, 0x4f, 0x45, 0x16, 0xa5, 0xde, 0x3c, 0x39, 0x93, 0xf9, 0xa8, 0xc1,
	0x24, 0xdf, 0x90, 0xa4, 0xea, 0xfe, 0x0b, 0x7f, 0xd6, 0x1e, 0xf7, 0xe8, 0x49, 0xa4, 0xfd, 0x1f,
	0x22, 0x99, 0x4c, 0x87, 0x11, 0x11, 0xbc, 0x0c, 0xdf, 0x7b, 0x33, 0x6f, 0x1e, 0xef, 0xf1, 0xc8,
	0xd2, 0x82, 0x0f, 0xc2, 0x14, 0xee, 0x13, 0x84, 0xa5, 0xc1, 0x0a, 0xb4, 0x17, 0x06, 0x2d, 0x36,
	0x8f, 0xab, 0x86, 0xae, 0x75, 0x21, 0x81, 0xd7, 0x0e, 0x03, 0xd2, 0x27, 0xd2, 0xe1, 0x17, 0x5d,
	0x94, 0x9e, 0x43, 0xed, 0x95, 0x46, 0xcb, 0xa3, 0x9e, 0x27, 0x7d, 0x92, 0xf3, 0xa8, 0x9c, 0x32,
	0x89, 0xde, 0xa0, 0x17, 0x65, 0xe1, 0x41, 0x7c, 0x5e, 0x95, 0x10, 0x8a, 0x95, 0x90, 0xa8, 0x6c,
	0xfa, 0xd1, 0xf4, 0x72, 0x87, 0x3b, 0x6c, 0x4e, 0x11, 0xaf, 0xc4, 0xce, 0x7f, 0x65, 0x64, 0x72,
	0x85, 0x16, 0x37, 0x01, 0x0c, 0x7d, 0x40, 0xc6, 0x2a, 0x80, 0xd9, 0x54, 0x79, 0x36, 0xcb, 0x16,
	0xa3, 0x6d, 0x8b, 0xe8, 0x25, 0x39, 0x0b, 0x2a, 0x68, 0xc8, 0xef, 0xcc, 0xb2, 0xc5, 0xbd, 0x6d,
	0x02, 0x74, 0x46, 0xce, 0x2b, 0xf0, 0xd2, 0xa9, 0x3a, 0x28, 0xb4, 0xf9, 0xb0, 0x79, 0xd7, 0xa7,
	0xe8, 0x63, 0x72, 0xe1, 0x41, 0x6b, 0x70, 0x2f, 0xab, 0xca, 0x81, 0xf7, 0xf9, 0xa8, 0xf9, 0xe6,
	0x4f, 0x92, 0x3e, 0x27, 0x13, 0xa3, 0xec, 0x5b, 0xa7, 0x24, 0xe4, 0x67, 0xb3, 0xe1, 0xe2, 0xfc,
	0xe9, 0x43, 0x9e, 0xb2, 0xf0, 0x98, 0x85, 0xb7, 0x59, 0xf8, 0x2b, 0x54, 0x76, 0x3d, 0xba, 0xf9,
	0xf1, 0x68, 0xb0, 0xed, 0x04, 0xf4, 0x05, 0x21, 0x12, 0xb5, 0x2e, 0x02, 0xb8, 0x42, 0xe7, 0xe3,
	0xff, 0x93, 0xf7, 0x24, 0x73, 0x20, 0x17, 0x31, 0xff, 0x3b, 0xd0, 0xfa, 0x8d, 0xab, 0xc0, 0xc5,
	0x58, 0xfe, 0x04, 0xba, 0x26, 0xfa, 0x14, 0x9d, 0x92, 0x49, 0x4a, 0xb0, 0xa9, 0x9a, 0x46, 0x46,
	0xdb, 0x0e, 0xf7, 0x2a, 0x1c, 0xf6, 0x2b, 0x9c, 0x7f, 0x20, 0xf7, 0xa3, 0xcd, 0x7a, 0x7f, 0x9d,
	0x5c, 0x18, 0x21, 0x65, 0x7b, 0x77, 0x26, 0x3d, 0x86, 0xe6, 0xe4, 0x6e, 0xb9, 0xbf, 0xee, 0x59,
	0x9c, 0xe0, 0xbf, 0x1c, 0xd6, 0xaf, 0x6f, 0x0e, 0x2c, 0xbb, 0x3d, 0xb0, 0xec, 0xe7, 0x81, 0x65,
	0xdf, 0x8e, 0x6c, 0x70, 0x7b, 0x64, 0x83, 0xef, 0x47, 0x36, 0x78, 0xbf, 0xda, 0xa9, 0xf0, 0x71,
	0x5f, 0x72, 0x89, 0x46, 0xc4, 0x35, 0x2d, 0xe3, 0x9c, 0x44, 0x3b, 0x27, 0xf1, 0x55, 0xfc, 0x3d,
	0xc8, 0x72, 0xdc, 0xac, 0xe3, 0xd9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x48, 0x40, 0x43,
	0xad, 0x02, 0x00, 0x00,
}

func (m *MonoItem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MonoItem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MonoItem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Collateral) > 0 {
		for iNdEx := len(m.Collateral) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Collateral[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMonoMarketplace(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.MinPrice) > 0 {
		for iNdEx := len(m.MinPrice) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MinPrice[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMonoMarketplace(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.SellerAddress) > 0 {
		i -= len(m.SellerAddress)
		copy(dAtA[i:], m.SellerAddress)
		i = encodeVarintMonoMarketplace(dAtA, i, uint64(len(m.SellerAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintMonoMarketplace(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintMonoMarketplace(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if m.ItemId != 0 {
		i = encodeVarintMonoMarketplace(dAtA, i, uint64(m.ItemId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MonoSellOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MonoSellOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MonoSellOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ItemId != 0 {
		i = encodeVarintMonoMarketplace(dAtA, i, uint64(m.ItemId))
		i--
		dAtA[i] = 0x18
	}
	if m.SellerId != 0 {
		i = encodeVarintMonoMarketplace(dAtA, i, uint64(m.SellerId))
		i--
		dAtA[i] = 0x10
	}
	if m.SellOrderId != 0 {
		i = encodeVarintMonoMarketplace(dAtA, i, uint64(m.SellOrderId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MonoBuyOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MonoBuyOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MonoBuyOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ItemId != 0 {
		i = encodeVarintMonoMarketplace(dAtA, i, uint64(m.ItemId))
		i--
		dAtA[i] = 0x18
	}
	if m.BuyerId != 0 {
		i = encodeVarintMonoMarketplace(dAtA, i, uint64(m.BuyerId))
		i--
		dAtA[i] = 0x10
	}
	if m.BuyOrderId != 0 {
		i = encodeVarintMonoMarketplace(dAtA, i, uint64(m.BuyOrderId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMonoMarketplace(dAtA []byte, offset int, v uint64) int {
	offset -= sovMonoMarketplace(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MonoItem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ItemId != 0 {
		n += 1 + sovMonoMarketplace(uint64(m.ItemId))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovMonoMarketplace(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovMonoMarketplace(uint64(l))
	}
	l = len(m.SellerAddress)
	if l > 0 {
		n += 1 + l + sovMonoMarketplace(uint64(l))
	}
	if len(m.MinPrice) > 0 {
		for _, e := range m.MinPrice {
			l = e.Size()
			n += 1 + l + sovMonoMarketplace(uint64(l))
		}
	}
	if len(m.Collateral) > 0 {
		for _, e := range m.Collateral {
			l = e.Size()
			n += 1 + l + sovMonoMarketplace(uint64(l))
		}
	}
	return n
}

func (m *MonoSellOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SellOrderId != 0 {
		n += 1 + sovMonoMarketplace(uint64(m.SellOrderId))
	}
	if m.SellerId != 0 {
		n += 1 + sovMonoMarketplace(uint64(m.SellerId))
	}
	if m.ItemId != 0 {
		n += 1 + sovMonoMarketplace(uint64(m.ItemId))
	}
	return n
}

func (m *MonoBuyOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BuyOrderId != 0 {
		n += 1 + sovMonoMarketplace(uint64(m.BuyOrderId))
	}
	if m.BuyerId != 0 {
		n += 1 + sovMonoMarketplace(uint64(m.BuyerId))
	}
	if m.ItemId != 0 {
		n += 1 + sovMonoMarketplace(uint64(m.ItemId))
	}
	return n
}

func sovMonoMarketplace(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMonoMarketplace(x uint64) (n int) {
	return sovMonoMarketplace(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MonoItem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonoMarketplace
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MonoItem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MonoItem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ItemId", wireType)
			}
			m.ItemId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ItemId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMonoMarketplace
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMonoMarketplace
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMonoMarketplace
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMonoMarketplace
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMonoMarketplace
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMonoMarketplace
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SellerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonoMarketplace
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonoMarketplace
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinPrice = append(m.MinPrice, types.Coin{})
			if err := m.MinPrice[len(m.MinPrice)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonoMarketplace
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMonoMarketplace
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Collateral = append(m.Collateral, types.Coin{})
			if err := m.Collateral[len(m.Collateral)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMonoMarketplace(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonoMarketplace
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MonoSellOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonoMarketplace
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MonoSellOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MonoSellOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellOrderId", wireType)
			}
			m.SellOrderId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SellOrderId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellerId", wireType)
			}
			m.SellerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SellerId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ItemId", wireType)
			}
			m.ItemId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ItemId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMonoMarketplace(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonoMarketplace
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MonoBuyOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonoMarketplace
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MonoBuyOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MonoBuyOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyOrderId", wireType)
			}
			m.BuyOrderId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BuyOrderId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerId", wireType)
			}
			m.BuyerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BuyerId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ItemId", wireType)
			}
			m.ItemId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ItemId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMonoMarketplace(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMonoMarketplace
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMonoMarketplace(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMonoMarketplace
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMonoMarketplace
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMonoMarketplace
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMonoMarketplace
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMonoMarketplace
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMonoMarketplace        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMonoMarketplace          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMonoMarketplace = fmt.Errorf("proto: unexpected end of group")
)
